
export const FETCH_ALL = "FETCH_ALL"
export const ADD_NEW = "ADD_NEW"
export const UPDATE = "UPDATE"
export const DELETE = "DELETE"
export const GET_INVOICE = "GET_INVOICE"

export const FETCH_INVOICE_BY_USER = "FETCH_INVOICE_BY_USER"
export const FETCH_INVOICE_BY_CLIENT = "FETCH_INVOICE_BY_CLIENT"

export const GET_ORDER = "GET_ORDER"
export const FETCH_ORDERS = "FETCH_ORDERS"
export const FETCH_ORDER_BY_USER = "FETCH_ORDER_BY_USER"


export const GET_INVENTORY = "GET_INVENTORY"
export const FETCH_INVENTORY_BY_USER = "FETCH_INVENTORY_BY_USER"


export const ALL_CLIENTS = "ALL_CLIENTS"
export const UPDATE_CLIENT = "UPDATE_CLIENT"
export const DELETE_CLIENT = "DELETE_CLIENT"
export const ADD_NEW_CLIENT = "ADD_NEW_CLIENT"
export const FETCH_CLIENTS_BY_USER = 'FETCH_PROFILE_USER';

export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
export const UPDATE_USER = "UPDATE_USER"
export const FETCH_USERS = "FETCH_USERS"
export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"
export const FETCH_CLIENT = "FETCH_CLIENT"

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_BY_USER = 'FETCH_PROFILE_USER';
export const FETCH_PROFILES_BY_USER = 'FETCH_PROFILES_BY_USER';

export const GET_PRODUCT = 'GET_PRODUCT'
export const FETCH_PRODUCT_BY_USER = 'FETCH_PRODUCT_BY_USER'
export const GET_TRANSACTION = 'GET_TRANSACTION'

export const ADD_NEW_BOARD = 'ADD_NEW_BOARD'
export const UPDATE_BOARD = 'UPDATE_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_BOARDS = 'FETCH_BOARDS'

export const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN'
export const UPDATE_COLUMN = 'UPDATE_COLUMN'
export const DELETE_COLUMN = 'DELETE_COLUMN'
export const FETCH_COLUMN = 'FETCH_COLUMN'
export const FETCH_COLUMNS = 'FETCH_COLUMNS'